import Head from 'next/head'
import Navigation from '../components/nav'

const Header = () => (
    <div className="w-full my-2 px-3">
        <Head>
            {/* <title>CyberEd | Leads you to your future</title> */}
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/CyberEd.gif" />
            <link href="https://dipaaapi.github.io/personal.json" />
            <script src="//unpkg.com/alpinejs" defer></script>
            <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        </Head>

        <Navigation />
    </div>
)

export default Header
