import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Skills: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Ed&lsquo;s Portfolio | Skills Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <meta name="viewport" content="initial-scale=1.0, width=device-width" />
            </Head>

            <main>
                <h1 className="">Skills Page</h1>
            </main>
        </div>
    )
}

export default Skills;